### ISSUE TITLE
Meetup 1

### ISSUE THREAD

**Issue by kracekumar** [rfcswelove/rfcs_we_love#1]
- Date: 28/01/2017
- Time: 12:00  to 15:00
- Venue: [Razorpay Office, Bangalore](https://where.rzp.io)
- Tweet: https://twitter.com/rfcs_we_love/status/817942585981435904
- RSVP: https://goo.gl/forms/iDuVnG7y6BlXo4ta2

### Talks

- [RFC 3629 (UTF-8)](https://tools.ietf.org/html/rfc3629) by [Chillar Anand](https://twitter.com/ChillarAnand)
- [RFC 6238 (TOTP)](https://tools.ietf.org/html/rfc6238) by [Govind](https://twitter.com/xgovindx)

**Comment by GoWind** [comment]
+1

**Comment by captn3m0** [comment]
Isn't 10-12 a short time? We usually do meetups between 12-5pm, and include lunch. We (@Razorpay) will be happy to sponsor lunch as long for 30 or so folks. Above that, and logistics get hard.

**Comment by kracekumar** [comment]
I expect a maximum of 10 people to attend. Though, I'm happy to see more people. I am ok to move the meetup to 12.00 and end by 3:00 PM. 5 PM looks a bit of stretch.

**Comment by jaseemabid** [comment]
Statistically afternoon worked better for PWL.  3pm sort of hits the sweet spot

**Comment by kracekumar** [comment]
For BangPypers 10:00AM to 1:00PM is the best turn out time.

**Comment by tallpants** [comment]
10-12 is kinda too short. 12 - 5 seems better like @captn3m0 said, more people will turn up and it'll be a more relaxed environment in the afternoon.

**Comment by kracekumar** [comment]
5 hours is too much for two talks. People can hang in after the meetup. I am skeptic to schedule a 5-hour meetup. I don't have any problem to start the meetup at 12.00. The timing is modified now. It's from 12:00 AM to 3:00 PM

**Comment by tallpants** [comment]
@kracekumar you mean 12:00 PM :laughing:

**Comment by captn3m0** [comment]
12-3 LGTM. I'll setup something for RSVP.

**Comment by kracekumar** [comment]
:+1:

**Comment by GoWind** [comment]
+1 for 12-3.

**Comment by hiemanshu** [comment]
LGTM. Will be there!

**Comment by saru95** [comment]
I'm a student. Is it fine, if I show up?

**Comment by ChillarAnand** [comment]
Yes, feel free to join the meetup.

Regards,
Chillar Anand
avilpage.com

**Comment by captn3m0** [comment]
RSVP Here: https://goo.gl/forms/iDuVnG7y6BlXo4ta2

**Comment by GoWind** [comment]
Code implementation for rfc 6238 : https://gist.github.com/GoWind/97cc76e3aa20b4c40e7c1c7bb74568ad

**Comment by captn3m0** [comment]
@ChillarAnand Can you share your slides for the talk please?

**Comment by kracekumar** [comment]
@captn3m0 : https://github.com/rfcswelove/rfcs_we_love/pull/3

**Comment by captn3m0** [comment]
Oh shit! Somehow missed that. I setup a channel on youtube and was doing the periscope -> Youtube uploads. Thanks for pointing this before I re-did this talk!
