### ISSUE TITLE
Plan for May 5th RFCs We Love meetup

### ISSUE THREAD

**Issue by dhruvdhody** [rfcswelove/rfcs_we_love#12]
Hi, 

Let's have our next RFCs we love meetup on 5th May, 10 AM to 1PM.  
Vinayak has confirmed zoomcar office (i think in indiranagar) would be the venue. 

Lets keep this IoT specific and Vinayak could introduce the interesting work they are doing at Zoomcar. We could also open call for topics related to IOT RFCs/WG/projects. 

What do you guys think?

**Comment by nyrahul** [comment]
IoT specific would be nice. Unfortunately i m not in town that whole week, so can't attend.
Would have loved to know what Zoomcar is doing!

**Comment by captn3m0** [comment]
Sounds great to me. Anyone else has proposals/suggestions for talks?

**Comment by vipulmathur** [comment]
I should be around. Not sure about topics, but IoT related RFCs sound good. Did we find any speakers yet? Let us put out the suggested topics/ call for speakers soon.

**Comment by dhruvdhody** [comment]
I received responses from a few saying that the weekend of 5th may is hard to attend, Vinayak suggested moving to the weekend after that i.e. 12th may saturday! I think it is a good idea! Any issues in moving the date?

**Comment by captn3m0** [comment]
I'll tweet it out and ask for proposals?

**Comment by nyrahul** [comment]
Hello All, There is a project that small team (including me) has been working on related to IoT.
https://github.com/whitefield-framework/whitefield
Would be great if you could skim-thru and to have some feedback/discussion when we meet. We have used this project during IETF hackathons and in context to some standards proposals primarily in the IoT working groups.

**Comment by dhruvdhody** [comment]
I was thinking to make a first draft of agenda with Items from Vinayak,
Rahul, Anmol etc recived so far and with a few slots open to ask for people
to propose more topics in! I hope to have this ready by EoD and we could
also propose the date change in the same email.

**Comment by KotaHemanthIITD** [comment]
Is 12th may, 2018 finalised for Meetup  ? Can you share location too?

**Comment by dhruvdhody** [comment]
Its actually 19th! 

see all the details at - https://docs.google.com/document/d/12YdBD10HGWTElL_93Z4TQGQ8abJsSo-mmgzEw62pt9c/edit#heading=h.gfy0z53hl9pf

**Comment by KotaHemanthIITD** [comment]
Gr8 ! thanks for the info
