### ISSUE TITLE
Grant commit rights to the repo

### ISSUE THREAD

**Issue by kracekumar** [rfcswelove/rfcs_we_love#14]
As of now, @captn3m0 and I, are available to merge any PR. In the interest of adding more active members who are organizing and attending the meetup. it's good time to add new collaborators.

I can think of @dhruvdhody-huawei, @vipulmathur, and Vinayak. Anyone else?

**Comment by captn3m0** [comment]
Good idea :+1: 

Adding the above 3. Will leave this open in case there are more suggestions.

**Comment by dhruvdhody** [comment]
adding @nyrahul - Rahul Arvind Jadhav to the list.

Thanks!

**Comment by captn3m0** [comment]
Sent an invite to @nyrahul.

@jaseemabid you also have an invite :+1:
