### ISSUE TITLE
Meetup 8

### ISSUE THREAD

**Issue by dhruvdhody** [rfcswelove/rfcs_we_love#16]
Date: 19th Jan (Saturday)
Time: 10 AM to 1 PM
Venue: [Center for Internet Society](https://cis-india.org/), Bangalore
Map: https://goo.gl/maps/Ye3mc1XbEvC2

RSVP: https://docs.google.com/forms/d/e/1FAIpQLScNGGKpNQbWUiJ76AeENNiR3qXaXr68LzS-UR-YO-236nPPsA/viewform

**Comment by dhruvdhody** [comment]
Some agenda items: 

- DC Routing and LSVR by Kannan, Cisco
- [Bit Indexed Explicit Replication](https://tools.ietf.org/html/rfc8401) (RFC8401) by Senthil, Huawei

**Comment by captn3m0** [comment]
I'd like to propose an overview of [Kubernetes CNI Specification](https://github.com/containernetworking/cni/blob/master/SPEC.md). It requires some fundamental understanding of Kubernetes / Linux Networking though.

I can share reading links if we go ahead with it.
