### ISSUE TITLE
Meetup 9 (Feb-Mar 2019) Transport and Applications

### ISSUE THREAD

**Issue by dhruvdhody** [rfcswelove/rfcs_we_love#17]
Transport protocols, mobile networking and application-level networking libraries. 
Speakers solicited on application-layer and transport-layer topics such as:

1) Transport layer protocols: HTTP/2 , QUIC
2) Secure UDP
3) TLS and crypto
4) Application frameworks such as OkHttp3
5) Best practices for networking performance on 4G LTE/3G 
6) Practical networking stacks for IoT devices and people-mobility platforms
7) Data privacy at rest and in transit: Policy and/or technology strategy.

Date: 2 March 2019 (saturday)
Venue: Gojek, 4th & 6th Floor Tower B, Diamond District, HAL Old Airport Road, Bengaluru, Karnataka 560008

**Comment by gurshabad** [comment]
Would like to propose a session on SNI encryption in TLS.

https://datatracker.ietf.org/doc/draft-ietf-tls-sni-encryption/
https://datatracker.ietf.org/doc/draft-ietf-tls-esni/

**Comment by nyrahul** [comment]
I would like to propose and present state of multi-path transports.
1. MPTCP and the design rationales RFC6824
2. Updates to MPTCP 6824bis
3. MPQUIC and the design rationale
4. Design/Deployment issues/experiences with MPTCP and MPUDP transports
5. System engineering challenges with multipath transports

**Comment by sid6mathur** [comment]
@dhruvdhody-huawei Can we add the RSVP link ( I am sending people to this Github issue) 
You may use this: https://www.meetup.com/Bangalore-Mobile-Performance-Group/events/257917522/

**Comment by dhruvdhody** [comment]
RSVP - https://goo.gl/forms/shTweoCPzV4c6pS92

**Comment by dhruvdhody** [comment]
The date is set for 2nd march 2019

**Comment by tekjar** [comment]
@dhruvdhody-huawei Happy to organize this at Ather Energy's main office at IBC knowledge park if you need space

**Comment by dhruvdhody** [comment]
@tekjar - Thanks for the offer, i will keep that as a backup, hoping to get a venue in Indiranagar/Domlur as many found that to be most central.
