### ISSUE TITLE
April 2019 Meetup

### ISSUE THREAD

**Issue by dhruvdhody** [rfcswelove/rfcs_we_love#18]
Proposed Date: 27th April 2019
Time: 11 AM to 2 PM 
Venue: TBD

We should include - Updates from IETF 104 (combined pitch in from those who attended IETF 104)

If someone has a topic in mind, please suggest with speakers etc.

**Comment by dhruvdhody** [comment]
In the past we have done these based on a theme (Data Center, IoT etc)
but that is not mandatory and we could also keep them as a mixed bag!

**Comment by nyrahul** [comment]
Security challenges on WSNs/WiFi/BLE networks .. MUD, EDHOC, OSCORE, WPA, PANA.. Possible attacks. Multicast Security options.

Mohit Sethi shared his talk sometime back on WiFi security and i wonder if we could get him to talk (remotely). Also would like to hear from other experts locally.

> Proposed Date: 27th April 2019
> Time: 11 AM to 2 PM
> Venue: TBD
> 
> We should include - Updates from IETF 104 (combined pitch in from those who attended IETF 104)
> 
> If someone has a topic in mind, please suggest with speakers etc.

**Comment by dhruvdhody** [comment]
Great suggestions @nyrahul, do we know any local experts working in similar area?

**Comment by dhruvdhody** [comment]
I have written to Tiru, seeing if he is interested.

**Comment by dhruvdhody** [comment]
Tiru can talk about mechanisms to automatically bootstrap endpoints (e.g., hosts, IoT devices) to discover and authenticate DNS-over-(D)TLS and DNS-over-HTTPS servers provided by a local network https://tools.ietf.org/html/draft-reddy-dprive-bootstrap-dns-server-02  or DOTS (DDoS open threat signaling) https://datatracker.ietf.org/wg/dots/documents/.

**Comment by dhruvdhody** [comment]
Maybe we make this a security focus meetup then!
