### ISSUE TITLE
June 2019 meetup

### ISSUE THREAD

**Issue by dhruvdhody** [rfcswelove/rfcs_we_love#19]
Proposed Date: 22nd June
Time: 10:30 AM to 1:30 PM
Venue: TBD

Lets finalize on theme and a key topic and we can build the agenda around it.

**Comment by captn3m0** [comment]
Rootconf falls on 21/22nd June as well: https://hasgeek.com/rootconf/2019/#talks

**Comment by dhruvdhody** [comment]
Clash is unfortunate, but we have some speakers confirmed so lets keep it on this date for now!
