### ISSUE TITLE
Get a logo

### ISSUE THREAD

**Issue by captn3m0** [rfcswelove/rfcs_we_love#2]
Don't like the egg avatar on twitter.

**Comment by kracekumar** [comment]
+1 from my side. Know any creative folks to make  a logo?

**Comment by chaitanyanettem** [comment]
I made this super quickly in case you want to use something till you get a proper creative person - http://i.imgur.com/UWW654P.png

**Comment by captn3m0** [comment]
Set it on our twitter: https://twitter.com/rfcs_we_love

Thanks @chaitanyanettem :100: 

@kracekumar Can you give me admin access to the org please?

**Comment by kracekumar** [comment]
@captn3m0 Done.

**Comment by captn3m0** [comment]
Updated on github as well.
