### ISSUE TITLE
Meetup 2

### ISSUE THREAD

**Issue by captn3m0** [rfcswelove/rfcs_we_love#5]
- Date: 26/02/2017
- Time: 12:00  to 15:00
- Venue: [Razorpay Office, Bangalore](https://where.rzp.io)
- Tweet: https://twitter.com/rfcs_we_love/status/832577836334489600
- RSVP: https://goo.gl/forms/a6EezvFbOlrQfCTR2

### Talks

- We are open for proposals. If you are interested in giving a talk about an RFC, please reply on this issue.

**Comment by captn3m0** [comment]
Proposing a talk on [HPACK (RFC 7541)](https://tools.ietf.org/html/rfc7541) - Header Compression for HTTP/2

**Comment by kracekumar** [comment]
Proposing a short talk on [Choosing a Name for Your Computer - RFC 1178](https://tools.ietf.org/html/rfc1178).

**Comment by kracekumar** [comment]
Details about [meetup 2](https://github.com/rfcswelove/rfcs_we_love#meetup-2).
