### ISSUE TITLE
Meetup 3

### ISSUE THREAD

**Issue by kracekumar** [rfcswelove/rfcs_we_love#6]
### Details

- Date: April 16th
- Venue: [Razorpay Office, Bangalore](https://where.rzp.io/)
- Time: 1:00 PM to 3:00 PM
- Twitter: https://twitter.com/rfcs_we_love/status/851659818561654785

### Agenda:

1. Introduction to [IIESoc](http://iiesoc.in/)
2. [RFC 7665](https://tools.ietf.org/html/rfc7665) - Service Function Chaining by Dhruv
3. Updates from [IEFT 98](https://www.ietf.org/meeting/98/index.html)
4. [RFC 7231 - Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content](https://tools.ietf.org/html/rfc7231) by Vinayakh

We're looking for speakers. If you're interested in talking, make a comment with a link to RFC. You can also upvote/heart the conversation as a symbol of RSVP.

**Comment by vinayakh** [comment]
I can talk on
1. Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content
https://tools.ietf.org/html/rfc7231

2. Pervasive Monitoring Is an Attack
https://tools.ietf.org/html/rfc7258

**Comment by kracekumar** [comment]
+1 for RFC7231. It appeals to a broad audience.

**Comment by dhruvdhody** [comment]
I can talk on - 

1. https://datatracker.ietf.org/doc/html/rfc4655 - Path Computation Element

2. https://tools.ietf.org/html/rfc7665 - Service Function Chaining

**Comment by kracekumar** [comment]
I added @vinayakh's talk. I feel the talk may take a good amount of time, at least an hour and a half. So I have made it as the last talk.

**Comment by kracekumar** [comment]
@dhruvdhody-huawei I am up for Service Function Chaining.

**Comment by kracekumar** [comment]
I added @dhruvdhody-huawei and @hiemanshu's talk.

@jaseemabid can you confirm the venue? 

@captn3m0 can we have razorpay as back up venue?

**Comment by captn3m0** [comment]
I might be unavailable on 9th. Paging @harman28 and @hashfyre as backup hosts. If either of them agrees, we should be good.

**Comment by ChillarAnand** [comment]
Can you update with slides/content?

**Comment by dhruvdhody** [comment]
Link to slides: https://github.com/dhruvdhody-huawei/ietf/blob/master/RFC%207665.pdf

**Comment by kracekumar** [comment]
Sldies and Video are included in [README](https://github.com/rfcswelove/rfcs_we_love/blob/master/README.md#meetup-3)
