### ISSUE TITLE
Time to plan another meetup

### ISSUE THREAD

**Issue by vipulmathur** [rfcswelove/rfcs_we_love#7]
It has been quite a while since the last meetup on Apr 23. When is the next one?

Is there interest in discussing some 'classic' related RFCs like:
- [RFC6202](https://tools.ietf.org/html/rfc6202): Known Issues and Best Practices for the Use of Long Polling and Streaming in Bidirectional HTTP
- [RFC6455](https://tools.ietf.org/html/rfc6455): The WebSocket Protocol

**Comment by vinayakh** [comment]
I am game. Will connect and see if we can get a venue for the next meeting.

**Comment by kracekumar** [comment]
Thanks @vipulmathur for kindling the discussion again. Let's do it. How about September 17th?

**Comment by vinayakh** [comment]
Can we do a Saturday (9th/16th) ? I talked to Smitha from Christ College. It can be a good venue.

**Comment by kracekumar** [comment]
Sure, let's do it on 9th.

**Comment by vipulmathur** [comment]
Saturday Sep 16th works best for me (can accommodate Sep 9th maybe).

**Comment by tallpants** [comment]
9th is good!

**Comment by kracekumar** [comment]
@vipulmathur Would you be interested to talk about both RFCs?

**Comment by vinayakh** [comment]
Confirming meetup venue on 9th Sep at Christ College 10am-12noon @vipulmathur @kracekumar @captn3m0

**Comment by kracekumar** [comment]
I'd like to go with @vipulmathur's choice.

**Comment by vinayakh** [comment]
@kracekumar I communicated with @vipulmathur off-thread and he confirmed 9th as well so I confirmed the venue for 9th Sept.

**Comment by kracekumar** [comment]
Awesome! What about speakers? @vinayakh @vipulmathur interested in talking?

**Comment by captn3m0** [comment]
Looks good to me.

**Comment by vipulmathur** [comment]
@kracekumar I can talk about both RFCs, but note that RFC6202 is a shorter one mostly dealing with pros and cons of streaming and long polling. We can cover that fully. RFC6455 however is the full WebSockets standards-track RFC. This is much longer and we can cover that only at high level. Think of the high-level view of RFC6455 as being to address some of the pros and cons highlighted in RFC6202. This material can be made to fit a 30-40min slot.

**Comment by vinayakh** [comment]
I have made a form for this - https://docs.google.com/forms/d/e/1FAIpQLSdvPc7H0z8vEEoySrGVvHe2h5oxWcRWhiGB4jQaz_OnF1Yhjw/viewform

@vipulmathur @kracekumar @captn3m0 Please review and we can start publicity.

**Comment by kracekumar** [comment]
@vipulmathur That looks good to go.

@vinayakh Looks good to me.

**Comment by vipulmathur** [comment]
It was a fun meetup!

I used [GitPitch](https://gitpitch.com) to prepare slides for the meetup. Use the following links to get access to the slides:
- [Slideshow](https://gitpitch.com/VipulMathur/rfc-meetup-sep2017?grs=gitlab)
- [Source](https://gitlab.com/VipulMathur/rfc-meetup-sep2017)

**Comment by kracekumar** [comment]
Thanks @vipulmathur for doing a talk, @vinayakh for finding a venue.

**Comment by kracekumar** [comment]
Links to the slides by @dhruvdhody-huawei

- https://github.com/dhruvdhody-huawei/iiesoc/blob/master/Introduction%20to%20IIESoc.pdf
- https://github.com/dhruvdhody-huawei/iiesoc/blob/master/Connections.pdf

Thank you, Dhruv.

**Comment by dhruvdhody** [comment]
Should we also update the main page https://github.com/rfcswelove/rfcs_we_love/ with these links too!

**Comment by captn3m0** [comment]
Filed a PR with the links: https://github.com/rfcswelove/rfcs_we_love/pull/9/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by kracekumar** [comment]
Good catch @dhruvdhody-huawei. Thanks @captn3m0
