### ISSUE TITLE
Plan for October month meetup  

### ISSUE THREAD

**Issue by kracekumar** [rfcswelove/rfcs_we_love#8]
Let's start planning for October month meetup.

### Agenda: 

- [ CoAP - RFC 7252](https://tools.ietf.org/html/rfc7252)
- [HMAC - RFC 2104](https://www.ietf.org/rfc/rfc2104)

### Venue: [Synup](http://bit.ly/old-synup-office)

Feel free to comment on any other details.

**Comment by vipulmathur** [comment]
@kracekumar will a venue in Whitefield be useful? I can ask if there is interest from the RFCs We Love group.

**Comment by kracekumar** [comment]
@vipulmathur Not really. Let's keep it in Kormanagala, JP/Jayanagar, Indira Nagar side.

**Comment by anmolsarma** [comment]
Proposing a talk on [CoAP (RFC 7252)](https://tools.ietf.org/html/rfc7252) - The Constrained Application Protocol

**Comment by kracekumar** [comment]
[Synup](https://goo.gl/maps/Qt4CzbTaxN62) has agreed to host us.

**Comment by kracekumar** [comment]
Thanks @anmolsarma for proposing the topic. Will an hour be enough to discuss the topic?

**Comment by kracekumar** [comment]
@vipulmathur @captn3m0 @vinayakh @dhruvdhody-huawei please suggest if the date and time work.

**Comment by anmolsarma** [comment]
@kracekumar yes, an hour will be enough.

**Comment by dhruvdhody** [comment]
I am not in town that weekend, so will not be able to attend! But if that date works best please continue!

**Comment by vipulmathur** [comment]
@kracekumar I will not be in town on 14th Oct. Please go ahead if others are available.

**Comment by captn3m0** [comment]
I'm free on 14th. I could speak on [HMAC - RFC2014](https://www.ietf.org/rfc/rfc2104) if we have time.

**Comment by kracekumar** [comment]
Let's have the meetup on 14th. Added both the talks to the agenda.
